### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by lanodan** [agateau/sfxr-qt#4]
Hi, I tried to compile sfxr-qt on gentoo amd64. And both HEAD and 1.1.0 are giving me this/theses error(s). And I don’t have much ideas on how to debug/solve it.

 I’m running on:
* Qt 5.7.1
* CMake 3.9.6
* Python (2.7.14, 3.4.5, 3.5.4*, 3.6.3) (*: default version)

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local ..
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found SDL: /usr/lib/libSDLmain.a;/usr/lib/libSDL.so;-lpthread (found version "1.2.15")
qpropgen: /usr/home/haelwenn/.local/bin/qpropgen
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/home/haelwenn/Sources/git/github.com/agateau/sfxr-qt/build
$ make
Scanning dependencies of target sfxr-qt_autogen
[  3%] Generating qrc_qml.cpp
[  6%] Generating core/basesound.h, core/basesound.cpp
Traceback (most recent call last):
  File "/usr/home/haelwenn/.local/bin/qpropgen", line 11, in <module>
    load_entry_point('qpropgen==0.1.0', 'console_scripts', 'qpropgen')()
  File "/usr/home/haelwenn/.local/lib64/python3.5/site-packages/qpropgen.py", line 126, in main
    template = env.get_template('template{}'.format(ext))
  File "/usr/lib64/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib64/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib64/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib64/python3.5/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: template.h
make[2]: *** [CMakeFiles/sfxr-qt_autogen.dir/build.make:80: core/basesound.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/sfxr-qt_autogen.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by agateau** [comment]
Hi! It looks like qpropgen cannot find its template files. There might be an install issue with it. Can you try removing|renaming `/usr/home/haelwenn/.local/bin/qpropgen` to use the bundled qpropgen instead? (be sure to update the qpropgen submodule first)

**Comment by agateau** [comment]
I think I fixed it. Since you installed qpropgen separately, you should install it again and then it should build. Feel free to reopen this issue if you still have issues
