### ISSUE TITLE
Crashes sometimes when clearing the LRU list in random order

### ISSUE THREAD

**Issue by sur5r** [agateau/sfxr-qt#8]
I was playing around with sfxr-qt today and experienced two crashes while deleting sounds from the list in the bottom left section of the window.

It seems it does NOT crash when deleting them exactly in order, but that's just me guessing.

Backtrace:
```
#0  0x00007f480d092903 in std::__atomic_base<int>::load (__m=std::memory_order_relaxed, this=0x6) at /usr/include/c++/10/bits/atomic_base.h:426
#1  QAtomicOps<int>::loadRelaxed<int> (_q_value=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h:239
#2  QBasicAtomicInteger<int>::loadRelaxed (this=0x6) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h:107
#3  QtPrivate::RefCount::deref (this=0x6) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h:66
#4  QString::~QString (this=0x7ffc3e137d60, __in_chrg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1307
#5  0x00007f480d2b8331 in QQmlSourceLocation::~QQmlSourceLocation (this=0x7ffc3e137d60, __in_chrg=<optimized out>) at ../../include/QtQml/5.15.2/QtQml/private/../../../../../src/qml/qml/qqmlglobal_p.h:358
#6  QQmlBinding::~QQmlBinding (this=0x7ffc3e137cd0, __in_chrg=<optimized out>) at qml/qqmlbinding.cpp:154
#7  0x00007f480d2bc07f in non-virtual thunk to GenericBinding<2>::~GenericBinding() () at qml/qqmlbinding.cpp:281
#8  0x000055901751ea26 in SoundListModel::data (this=<optimized out>, index=..., role=0) at ./core/SoundListModel.cpp:31
#9  0x00007f480556651f in QModelIndex::data (arole=0, this=0x7ffc3e137d70) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:460
#10 QQmlDMAbstractItemModelData::value (role=0, this=0x559019524010) at qqmladaptormodel.cpp:414
#11 QQmlDMCachedModelData::metaCall (this=0x559019524010, call=<optimized out>, id=<optimized out>, arguments=0x7ffc3e137e20) at qqmladaptormodel.cpp:282
#12 0x00007f480d17e561 in QQmlPropertyData::readPropertyWithArgs (this=<optimized out>, this=<optimized out>, args=0x7ffc3e137e20, target=0x559019524010) at ../../include/QtQml/5.15.2/QtQml/private/../../../../../src/qml/qml/qqmlpropertydata_p.h:285
#13 QQmlPropertyData::readPropertyWithArgs (args=0x7ffc3e137e20, target=0x559019524010, this=0x559019793d08) at ../../include/QtQml/5.15.2/QtQml/private/../../../../../src/qml/qml/qqmlpropertydata_p.h:360
#14 QQmlPropertyData::readProperty (property=0x7ffc3e137e00, target=0x559019524010, this=0x559019793d08) at ../../include/QtQml/5.15.2/QtQml/private/../../../../../src/qml/qml/qqmlpropertydata_p.h:357
#15 loadProperty (v4=0x559019206330, object=0x559019524010, property=...) at jsruntime/qv4qobjectwrapper.cpp:176
#16 0x00007f47f00152fc in ?? ()
#17 0x0000000000000000 in ?? ()

```

This is sfxr-qt 1.3.0+git20210422-2 on Debian bookworm.

**Comment by agateau** [comment]
Thanks for the report, looking into it.
